# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# Deny crates with security vulnerabilities
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
# Only check direct workspace dependencies for unmaintained status
unmaintained = "workspace"
# Warn about yanked crates but don't fail
yanked = "warn"
ignore = []

[licenses]
# Use cargo-deny v2 license configuration
# All licenses not explicitly allowed are denied by default
version = 2
# Allow common open-source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "GPL-3.0-or-later",
    "Unicode-DFS-2016",
    "Unicode-3.0",
]
confidence-threshold = 0.8

[bans]
# Deny multiple versions of the same crate
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = []
skip = []
skip-tree = []

[sources]
# Deny crates from unknown sources
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
