name: Client CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Bun runtime
      uses: oven-sh/setup-bun@v2
      with:
        version: latest

    - name: Install dependencies
      run: bun install
      working-directory: ./packages/client

    - name: Run lint
      run: bun run lint
      working-directory: ./packages/client

    - name: Run tests
      run: bun test
      working-directory: ./packages/client
